services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack:latest
    ports:
      # Port for all LocalStack services (Gateway)
      - "127.0.0.1:4566:4566"
    environment:
      # Enable specific services to speed up startup
      - SERVICES=s3,sns,sqs,iam
      - DEBUG=0
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack/ready.d/:/etc/localstack/init/ready.d
      - "/var/run/docker.sock:/var/run/docker.sock"


  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: eduardo
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./db:/var/lib/postgresql/data

# volumes:
#   my_pg_db: